version: "3.7"
services:
  emby_script:
    container_name: emby_scripts_3888
    image: hush114514/emby_scripts
    network_mode: bridge
    # OPTIONAL: 挂载tmdb缓存到容器外
    # volumes:
    #   - /your_localpath/tmdb_alt_name.json:/app/tmdb_alt_name.json
    #   - /your_localpath/country.json:/app/country.json
    #   - /your_localpath/tmdb.json:/app/tmdb.json
    environment:
      - TZ=Asia/Shanghai
      # EMBY地址
      - EMBY_HOST= http://xxx:8092
      # EMBY的API_KEY
      - EMBY_API_KEY=
      # EMBY的USERID
      - EMBY_USER_ID=
      # tmdb API 读访问令牌
      - TMDB_KEY=
      # 库名 多个时英文逗号分隔
      - LIB_NAME=
      # DRY_RUN = true时为预览, false实际运行
      - DRY_RUN=true
      # 运行间隔
      - RUN_INTERVAL_HOURS=24
      # 是否增加港台标题
      - ADD_HANT_TITLE=true
      # 是否启用各个模块
      - ENABLE_ALTERNATIVE_RENAMER=true
      - ENABLE_COUNTRY_SCAPTER=true
      - ENABLE_GENRE_MAPPER=true
      - ENABLE_SEASON_RENAMER=true
